create table clc_nomenclature (
	code varchar(4),
	lib varchar(100),
	primary key (code)
);
insert into clc_nomenclature values ('1','Territoires artificialisés');
insert into clc_nomenclature values ('11','Zones urbanisées');
insert into clc_nomenclature values ('111','Tissu urbain continu');
insert into clc_nomenclature values ('112','Tissu urbain discontinu');
insert into clc_nomenclature values ('12','Zones industrielles ou commerciales et réseaux de communication');
insert into clc_nomenclature values ('121','Zones industrielles et commerciales');
insert into clc_nomenclature values ('122','Réseaux routier et ferroviaire et espaces associés');
insert into clc_nomenclature values ('123','Zones portuaires');
insert into clc_nomenclature values ('124','Aéroports');
insert into clc_nomenclature values ('13','Mines, décharges et chantiers');
insert into clc_nomenclature values ('131','Extraction de matériaux');
insert into clc_nomenclature values ('132','Décharges');
insert into clc_nomenclature values ('133','Chantiers');
insert into clc_nomenclature values ('14','Espaces verts artificialisés, non agricoles');
insert into clc_nomenclature values ('141','Espaces verts urbains');
insert into clc_nomenclature values ('142','Équipements sportifs et de loisirs');
insert into clc_nomenclature values ('2','Territoires agricoles');
insert into clc_nomenclature values ('21','Terres arables');
insert into clc_nomenclature values ('211',e'Terres arables hors périmètres d\'irrigation');
insert into clc_nomenclature values ('212','Périmètres irrigués en permanence');
insert into clc_nomenclature values ('213','Rizières');
insert into clc_nomenclature values ('22','Cultures permanentes');
insert into clc_nomenclature values ('221','Vignobles');
insert into clc_nomenclature values ('222','Vergers et petits fruits');
insert into clc_nomenclature values ('223','Oliveraies');
insert into clc_nomenclature values ('23','Prairies');
insert into clc_nomenclature values ('231','Prairies');
insert into clc_nomenclature values ('24','Zones agricoles hétérogènes');
insert into clc_nomenclature values ('241','Cultures annuelles associées aux cultures permanentes');
insert into clc_nomenclature values ('242','Systèmes culturaux et parcellaires complexes');
insert into clc_nomenclature values ('243','Surfaces essentiellement agricoles, interrompues par des espaces naturels importants');
insert into clc_nomenclature values ('244','Territoires agro-forestiers');
insert into clc_nomenclature values ('3','Forêts et milieux semi-naturels');
insert into clc_nomenclature values ('31','Forêts');
insert into clc_nomenclature values ('311','Forêts de feuillus');
insert into clc_nomenclature values ('312','Forêts de conifères');
insert into clc_nomenclature values ('313','Forêts mélangées');
insert into clc_nomenclature values ('32','Milieux à végétation arbustive et/ou herbacée');
insert into clc_nomenclature values ('321','Pelouses et pâturages naturels');
insert into clc_nomenclature values ('322','Landes et broussailles');
insert into clc_nomenclature values ('323','Végétation sclérophylle');
insert into clc_nomenclature values ('324','Forêt et végétation arbustive en mutation');
insert into clc_nomenclature values ('33','Espaces ouverts, sans ou avec peu de végétation');
insert into clc_nomenclature values ('331','Plages, dunes et sable');
insert into clc_nomenclature values ('332','Roches nues');
insert into clc_nomenclature values ('333','Végétation clairsemée');
insert into clc_nomenclature values ('334','Zones incendiées');
insert into clc_nomenclature values ('335','Glaciers et neiges éternelles');
insert into clc_nomenclature values ('4','Zones humides');
insert into clc_nomenclature values ('41','Zones humides intérieures');
insert into clc_nomenclature values ('411','Marais intérieurs');
insert into clc_nomenclature values ('412','Tourbières');
insert into clc_nomenclature values ('42','Zones humides maritimes');
insert into clc_nomenclature values ('421','Marais maritimes');
insert into clc_nomenclature values ('422','Marais salants');
insert into clc_nomenclature values ('423','Zones intertidales');
insert into clc_nomenclature values ('5','Surfaces en eau');
insert into clc_nomenclature values ('51','Eaux continentales');
insert into clc_nomenclature values ('511',e'Cours d\'eau et voies d\'eau');
insert into clc_nomenclature values ('512',e'Plans d\'eau');
insert into clc_nomenclature values ('52','Eaux maritimes');
insert into clc_nomenclature values ('521','Lagunes littorales');
insert into clc_nomenclature values ('522','Estuaire');
insert into clc_nomenclature values ('523','Mers et océans');
insert into clc_nomenclature values ('950','Océan');
insert into clc_nomenclature values ('951','UE');
insert into clc_nomenclature values ('952','Hors UE');
insert into clc_nomenclature values ('999','Non classé');
